version: "3.9"
services: 
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports: 
     - 3366:3306
    restart: always
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=retail_bd
      - MYSQL_ROOT_PASSWORD=Admin12345
    networks:
      - retail-app-network
  springboot-app:
    container_name: springboot-app
    image: retail-app:1.0.0
    restart: on-failure
    build: .
    ports:
      - 8081:8080 
    environment:
      RDS_HOSTNAME: 'mysqldb'
      RDS_DB_NAME: 'retail_bd'
      RDS_USERNAME: 'root'
      RDS_PASSWORD: 'Admin12345'
      RDS_PORT: 3366
    depends_on:
      - mysqldb
    networks: 
      - retail-app-network      
networks:
  retail-app-network:
    driver: bridge